{% set name = "ptpython" %}
{% set version = "3.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ptpython-{{ version }}.tar.gz
  sha256: b9d625183aef93a673fc32cbe1c1fcaf51412e7a4f19590521cdaccadf25186e

build:
  noarch: python
  number: 1
  entry_points:
    - ptpython = ptpython.entry_points.run_ptpython:run
    - ptipython = ptpython.entry_points.run_ptipython:run
    - ptpython3 = ptpython.entry_points.run_ptpython:run
    - ptipython3 = ptpython.entry_points.run_ptipython:run
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - appdirs
    - black
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.43,<3.1.0
    - pygments
    - python

test:
  imports:
    - ptpython
    - ptpython.contrib
  commands:
    - pip check
    - ptpython --help
    - ptipython --help
    - ptpython3 --help
    - ptipython3 --help
  requires:
    - pip
    - python

about:
  home: https://github.com/prompt-toolkit/ptpython
  summary: Python REPL build on top of prompt_toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
    - Anthchirp
